### ISSUE TITLE
Create UI from JSON

### ISSUE THREAD

**Issue by willrogers** [dls-controls/cs-web-proto#30]
At the moment we need to hard-code our layout in `App.tsx`. We want to move to loading a JSON string.

There is a prototype implementation on the `factory` branch in https://github.com/willrogers/epics-web-proto/ - see 

https://github.com/willrogers/epics-web-proto/blob/factory/src/app.js

**Comment by TimGuiteDiamond** [comment]
Thinking about how to do this, based on Will's attempt and a known difficulty with CS-Studio

- React expects keys which last for the lifetime of the component when using map
- CS-Studio also expects unique component ID but some of our scripts struggle to generate this because they use the label as a key; for example Overlay 1-8 screens might all have "Input X" values but they have to be named "Input X 1", "Input X 2" ...

So the key should probably be specified as part of the object.

There is also a question of whether we should allow trees (like html) or demand a flat structure (like edm)

Possible tree layout:
```
abstract_widget = {
  widget type: string,
  id: string,
  x: number,
  y: number,
  width: number,
  height: number,
  children: List[abstract_widget]
}
```

Flat layout would be the same but with a special widget type for the top level display and no children for any of the widgets.

**Comment by willrogers** [comment]
I very much expect a tree-based layout as in CS-Studio.

**Comment by TimGuiteDiamond** [comment]
Yep, CS-Studio uses a schema similar to what I described above but instead of a list of children it just uses multiple <widget> tags. Not sure this would be possible or even desirable in Typescript.

Presumably it would be nice to have both the schema and rendering function defined so that they recursively add children?
Would be interesting to look at how this affects performance - when values are changed is the whole tree changed? Presumably not but perhaps there are some things we need to be mindful of

**Comment by TimGuiteDiamond** [comment]
See **positioning** branch for work on this 4ece2b469fb843bb70cb3752907cae16369e60a2
