### ISSUE TITLE
Positioning

### ISSUE THREAD

**Issue by willrogers** [dls-controls/cs-web-proto#42]
We need to be able to support both

* absolute positioning, pixel by pixel as in EDM and CS-Studio
* standard CSS layout

Absolute positioning is quite straightforward inside one div with position relative.

Standard CSS layout shouldn't be problematic, although you run into questions like the following: 

> CSS borders are outside of the element, whereas CS-Studio has borders inside the element. If you add a border, you need the internal element to render in a smaller size to appear inside that border. That's easiest to do with absolute positioning. Should we use absolute positioning _inside_ a widget? Then we might start having to calculate locations within the widget. Is that problematic?

This is tied into #37.

**Comment by TimGuiteDiamond** [comment]
@willrogers had addressed the above issue with the box-sizing: border-box css option which applies borders, padding etc internally rather than externally, giving a better representation of the absolute sizing provided.

I have now made a small change to the alarm border which allows it to expand to the size of the parent container if this is fixed, or otherwise to be sized according to the lowest component with a given size, for example a div readback or the input element.

Flexible positioning has also been demonstrated from JSON specifically with the use of a flex box container. This may also be applied to simply provide relative positioning.

The next step is to demonstrate mixing in multiple JSON files and providing them all with different macros.

**Comment by TimGuiteDiamond** [comment]
This issue is relevant in #51

**Comment by TimGuiteDiamond** [comment]
@willrogers I think we can close this now

**Comment by willrogers** [comment]
I think there's a lot more to explore for positioning, but let's close this ticket.
