### ISSUE TITLE
Generic routing to screens

### ISSUE THREAD

**Issue by TimGuiteDiamond** [dls-controls/cs-web-proto#75]
At the moment, our screens are all collected in App.tsx which has direct access to Page components which know exactly which JSON file to open.

It would be useful to add functionality to open any of the available JSON pages with given macroMaps and include this in the router context without having to explicitly create every page.

As an example use case, a button (or image) which opens another screen with a specified macro map, for use from the synoptic.

Most of the components are available for this, such as widgetFromJson, but it has not been implemented and may present some challenges.

This is an important and expected feature which we have not yet implemented.

**Comment by skyfrench** [comment]
#88 includes a demo of dynamic routing. 
With this we can add e.g.
`<Link to={'dynamic/ionpExample/{"device":"SR03A-VA-IONP-01"}'}></Link>`
around a button (e.g. basic graphical button added in #85) and it'll open a new screen.

A couple of points for discussion:

- Where should the new screens open? Relates to #74. Do we want to divide screens into regions and have 'component' screens able to open in any of those. Or a new window/pop-up? 
- Should clicking to open a new screen (instead of a generic web page) actually be an action? Should it then be that only 'action buttons' can open screens, or any type of button? 
Should there be a base 'WidgetButton' with options to be (any or all of the following):
-- graphical (displaying as an image from file, or line, or circle)
-- action-full (the two existing actions plus open new screen) 
-- context menu'd?

**Comment by TimGuiteDiamond** [comment]
Seems to work quite nicely, I guess moving towards the synoptic/embed/details layout is a detail that should be done later.
It really just depends where you instantiate the <Route> element

For the moment I think it would be nice to display this option via context menu on some kind of button, maybe add it to graphics later/for the demo?

**Comment by TimGuiteDiamond** [comment]
We have achieved this to a good level for the time being with the DynamicPage component, and `useHistory` hook encoding the address, pages and macros in the HTML address.

@skyfrench if you agree this is working well then we can close this issue
